# site settings
title: Maciej Kos
# subtitle: by HTML5 UP
email:
description: Personal website of Maciej Kos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maciejkos.github.io" # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Road
city: Brookline
state: MA
# zip_code: 55555
country: United States of America
# phone: (716) 555-5555

# social settings
500px_url:
facebook_url:
github_url: https://github.com/maciejkos
cv_url: https://maciejkos.github.io//assets//documents//Maciej Kos - resume - current.pdf
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/maciejkos/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mmaciek

# build settings
markdown: kramdown

sass:
  style: compressed
